sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: aYwMzePBRy2Saf6S4VwjNPhvGzZisbD/G+exsNE4ICqxmpYjDJ4eUB2I0OGWD4zq/CMp+KsP3NgyQ2SmEXwopjM9ihl9sNpGgSZsHcJMCphPJDJCKI1MOnq+bg9ChQWO3QPuenHeaBG50y5rEe469JjsNEicy2X+ANk+1Fc09/v260uXPHeuZMXaIXvl0DZfOOKJBwfqyUbILw4y3P2e/4yzCqn4aedTvoAhrha/xGB7Y3AgmojewKYPJmwEp32pF53MDWob2DpbxeYRQDJagp1cDwd5SpzMRMDJfclEAj32lGz8+jxk/EtV9+pnmXMjtXuB8+4cKM3EQPQ1wJ+kg3Ym6ECviY2HzVKgw0KoXQAqIV5OA3Cc1VAtUxPlUuNNa5jF5yOgBsjHVWLbOquvUbc9uh3EC8LsrfuLmRXLkspZVVRnenP292+2zcM0iOtb/d4DaojE1lOnXoHoLTySGSxk0TbgHPbaWtDTl2TmfhIzFC4lV7xbGD1GuMj4gfYvpoPm7nUXdHnRnHdKQ0fctta95TYIOkByGQfsAHz+ZwNfUCmP6yjUtfHqflTyzt5LlrPr4Dj8badnb6BTsQgrUQBmxlqCyWadekkHljlUOoqcTJfdam28Nq9P646qdRZkLxyyGOk5GJ+sjUezYfZU4T5TUyDRgnnMX5/xvYVPuY0=
  - secure: jO1Mc/LjELbwKGIUoyljIyj/ZVKZAhogAuhfBZjP2aYMoeuSg2RNMGH3Rj8yLiduijZSIW1a7MXL2ZpaSf8qfDdtKrPhqonyMVDr+BW+/m0wisz4+hkwFRs84wnJEUmrs3grR5o6FdsJe2Xc2Y4upRWRCVtLN9BQH8Oupg4S0I12nY2o+D9Hd7CrIhSyvc8w9NoRzrwPIdWAYF2NNrvVFuQ1IXjwBS1GzjiMcOGvSFsAxizZCvs6HnFkHwYaKbAy90dIlqxjpsPkw8bo7YBCu5O7O/Le7u2aoKogHUEa5WanIfFikQLAWIvHs1KYdkxjx7D+bwzU0FmEiKFl3QX6+bZ18ZaoIUaFiGbjQtTrY9mDAhJnryvqgC5Ou/tmGQ4bYv2pTJXp1M0DCPWkH2RgRz+GirdkiP6oFtH65v6kQekJdrZPZQ3puR7otB5uIt7yaK56u66AlxTGDXZRhekAqXu11dtdDh86uRlYFg6jeWrGPhjDcqkpKSZDyMvtmkvxzDvZAHCyz/F8kcJTdxRiWKaYUdU4QrbwQ2dklh0T8pYNdvJe6EhNOsd1hD/iHZkVxLR78yX8osiYWGipDIQEX1rspuiWSw8y3VVtWASkoagwPUMKYvumYlxwmR2uXwqJ6qdnWzKePcSgg79jz/YcEVF8XEuMZ9khbrT/sTTpZlg=
